// angular-library/src/app/edit-book/edit-book.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Book } from 'src/Book';
import { DataManagerService } from '../data-manager.service';
@Component({
  selector: 'app-edit-book',
  templateUrl: './edit-book.component.html',
  styleUrls: ['./edit-book.component.css'],
})
export class EditBookComponent implements OnInit {
  id: string;
  book: Book;
  constructor(
    private route: ActivatedRoute,
    private dataService: DataManagerService
  ) {
    this.id = route.snapshot.params['id'];
  }

  ngOnInit(): void {
    this.dataService.getBooks(this.id).subscribe((data) => {

      this.book = data[0];
    });
  }
  onEdit() {
    
  }
}

<mat-card class="component-heading">
  <h2>Edit A Book</h2>
</mat-card>

<mat-card class="card-container">
  <form class="form">
    <div class="grid">
      <div class="full-width">
        <mat-form-field>
          <mat-label>Title</mat-label>
          <input matInput placeholder="ex. Harry Potter" [value]="book?.title" />
        </mat-form-field>
      </div>

      <div class="half-width">
        <mat-form-field>
          <mat-label>Author</mat-label>
          <input matInput [value]="book?.author"/>
        </mat-form-field>
      </div>

      <div class="half-width">
        <mat-form-field>
          <mat-label>UUID</mat-label>
          <input matInput [value]="book?.UUID"/>
        </mat-form-field>
      </div>

      <div class="half-width">
        <mat-form-field>
          <mat-label>Date</mat-label>
          <input matInput  [value]="book?.date"/>
        </mat-form-field>
      </div>

      <div class="half-width">
        <mat-form-field>
          <mat-label>Cover Image URL</mat-label>
          <input matInput [value]="book?.cover" />
        </mat-form-field>
      </div>
      <div class="full-width">
        <mat-form-field>
          <mat-label>Summary</mat-label>
          <textarea matInput [value]="book?.summary">

            </textarea>
        </mat-form-field>
      </div>


      <div class="full-width button">
        <button mat-raised-button color="primary">Edit</button>
      </div>
    </div>
  </form>
</mat-card>

// react-library/src/components/EditBook.tsx
import React, { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import { Book } from "../Book";
import { createStyles, makeStyles, Theme } from "@material-ui/core/styles";
import { Card, TextField, Grid, Button } from "@material-ui/core";
import axios from "axios";

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      flexGrow: 1,
      width: "80%",
      textAlign: "center",
      margin: "auto",
    },
    heading: {
      width: "50%",
      background: "#081C8D",
      textAlign: "center",
      color: "#FFFFFF",
      margin: "auto",
      marginBottom: "50px",
      "& h1": {
        margin: "auto",
      },
    },

    input: {
      width: "100%",
    },
    button: {
      width: "100%",
      fontWeight: 700,
    },
  })
);
const EditBook = () => {
  const classes = useStyles();
  const { id }: { id: string } = useParams();
  const [book, setBook] = useState<Book>();
  useEffect(() => {
    (async () => {
      const data = await axios({ method: "get", url: `http://localhost:8000/books/${id}` });
      setBook(data.data[0]);
    })();
  },[id]);

  return (
    <form className={classes.root} noValidate autoComplete="off">
      <div>
        <Card className={classes.heading}>
          <h1>Edit a Books</h1>
        </Card>
        <form action="" className={classes.root}>
          <Grid container spacing={1}>
            <Grid item xs={12}>
              <TextField
                InputLabelProps={{
                  shrink: true,
                }}
                className={classes.input}
                required
                id="outlined-required"
                value={book?.title}
                label="Book Title"
                placeholder="enter the book's title "
                variant="outlined"
              />
            </Grid>
            <Grid item xs={6}>
              <TextField
                InputLabelProps={{
                  shrink: true,
                }}
                className={classes.input}
                value={book?.author}
                label="Author"
                placeholder="enter the book's author"
                variant="outlined"
              />
            </Grid>
            <Grid item xs={6}>
              <TextField
                InputLabelProps={{
                  shrink: true,
                }}
                className={classes.input}
                value={book?.UUID}
                required
                id="outlined-required"
                label="UUID"
                placeholder="enter the book's UUID "
                variant="outlined"
              />
            </Grid>
            <Grid item xs={6}>
              <TextField
                InputLabelProps={{
                  shrink: true,
                }}
                className={classes.input}
                value={book?.date}
                label="Date"
                placeholder="enter the book's date"
                variant="outlined"
              />
            </Grid>
            <Grid item xs={6}>
              <TextField
                InputLabelProps={{
                  shrink: true,
                }}
                className={classes.input}
                value={book?.cover}
                label="Cover image url"
                placeholder="enter the book's cover url "
                variant="outlined"
              />
            </Grid>
            <Grid item xs={12}>
              <TextField
                InputLabelProps={{
                  shrink: true,
                }}
                className={classes.input}
                value={book?.summary}
                multiline
                id="outlined-textarea"
                label="Summary"
                placeholder="enter the book's summary "
                variant="outlined"
              />
            </Grid>
            <Grid item xs={12}>
              <Button className={classes.button} variant="contained" color="primary" type="submit">
                Submit
              </Button>
            </Grid>
          </Grid>
        </form>
      </div>
    </form>
  );
};

export default EditBook;
